### ISSUE TITLE
Identifying the focus of OpenGraphics

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenGraphics#16]
So far there have been several efforts to create a workflow for the OpenGraphics projects. Most of our efforts are currently separate and use different pieces of software, setups, and workflows. Each of these workflows with its own strengths that are tied to the beliefs of its creators.

Over the past few years, we've had countless discussions about how to move this project forward, things like the importance of recreating the original style, upping the scale, and Blender versions are topics that often come up anytime one of us gives it another go.

This project is a massive undertaking, and due to the complexity of the sprites, we will not be able to rely on pixel art for asset creation (Like for OpenTTD's initial replacement graphics OpenGFX). Instead, we will have to rely on a process for rendering sprites from 3D models and animations consistently. 

We can split up the pipeline into 2 segments that may be able to work independently from each other:
- 3D asset creation
- Rendering process

My suggestion would be that we each note down what our personal focus is. What boxes would the OpenGraphics pipeline have to tick to satisfy your personal beliefs about what the OpenGraphics project should become and achieve. 
Additionally, explain what you've experimented with so far, and what the strengths of your process are.

This will hopefully allow us to bundle our efforts, strengths and believes in one place, which will make it easier for new contributors to get an idea for where we're at. 
From there I'd like to split up the discussion into separate topics to hopefully come to conclusions about how we would like to tackle the individual components that make up the OpenGraphics project.

**For this first stage, please refrain from discussing people their personal beliefs. We'll get to that once we've gathered enough input.**

Here's a suggestion for the format you can use for your response:
```
### Personal Beliefs
What should OpenGraphics aim to achieve? What aspects do you believe will be most important to consider?

### Personal Experience
What have you tried already? What are your project's strengths and purposes?
```

[22-05-2021] **You may now discuss and suggest separate discussion topics** https://github.com/OpenRCT2/OpenGraphics/issues/16#issuecomment-846416920

**Comment by frutiemax** [comment]
Most important is consistency across OpenGraphics assets and target a style close to vanilla RCT2. WW and TT assets are not the top priority tbh.

**Comment by oli414** [comment]
**Personal Beliefs**
- My biggest priority would be to create a render pipeline that is capable of mimicking the vanilla graphics as closely as possible. There will be a very long time in which we will not have replaced all the graphics, and we need to ensure that the new graphics are consistent with the existing graphics, and graphics from previously created user-generated content.
- Whilst new graphics do need to mimick the look and feel of the original graphics, we do not need to fully replicate the exact form and colors of each individual object. However, we shouldn't stray too far from the meaning of the original. While a hotdog stand without the hotdog on top would be more realistic, it might pose challenges to the gameplay if all the stalls are plain buildings.
- The process should be automated as much as possible, for example, to render all the animations and angles for a complex coaster type in the right order.
- However: The process needs to be malleable, creating graphics is a creative process, and sadly one size (fixed pipeline) doesn't fit all. We need to support small changes to the lighting and rendering, as well as post-process edits. I highly suspect Simon Foster had to sometimes go in to make some manual pixel changes for example to make pieces tile properly.

**Personal Experience**
I'm the creator of Blender-RCT-Graphics. A Blender plugin and setup that is optimized to easily render all the separate sprites needed for various objects and rides, as well as mimicking the original graphics as closely as possible.
My goal with this project was to both be used as a tool for custom scenery/ride creation, as well as a setup that could be used for the OpenGraphics project.

https://github.com/oli414/Blender-RCT-Graphics

With this plugin people would be able to create their ride vehicle as a 3D object. Next, the user would select the track sections that the ride vehicle would have to be able to traverse. To then simply press "Render" for the plugin to automatically render every required angle.
The plugin would output to a file that was immediately cropped and quantized using ImageMagick, leaving you with hundreds of sprites ready to be loaded into the game.

The most important aspects of this project were:
- Automation, providing an easier way to render all the layers and angles needed
- Consistency, the lighting rig, and render setup were highly optimized to mimic the original graphics as closely as possible

Currently, the tool only works in an outdated version of Blender due to the 2.8 Blender update that removed Blender Render, the original scanline renderer.

![image](https://user-images.githubusercontent.com/2348094/117548675-7f931400-b036-11eb-8bc5-ec0b2b77f3b5.png)

![image](https://user-images.githubusercontent.com/2348094/117548643-58d4dd80-b036-11eb-9881-49c6ba4dc8c5.png)

**Comment by Ryder17z** [comment]
>     * Whilst new graphics do need to mimick the look and feel of the original graphics, we do not need to fully replicate the exact form and colors of each individual object. 

So potentially the god-awful-looking looping coaster train could potentially get replaced with something closer to the rct1 version?

**Comment by nfeho** [comment]
**Personal Beliefs**

- I think we should aim to replicate the original graphics to be as close as possible. But I also think, that we should expand the possibillites for players to use the new objects in new ways.

- An example of these new possibillities I would like to mention the recolorable trees I made (screenshot below). I think that most of the scenery pieces should be recolorable.

- Tracks, that have missing sprites for track elements should be added, but as a separate track type to the original. That would eliminate breaking already saved parks while also providing a possibility to build these tracks with new elements.

**Personal Experience and Aim**

- I have made small trees with usage of **fruitemax's Blender setup**, which works with Blender 2.8 and above. His setup is ideal for making foliage in the style that resembles the original art style. I can't speak much more for his setup, I believe he understands the strengths and weaknesses of his setup more than I do.

- I am aiming at recreating small trees and foliage, some small scenery pieces, walls, fences, etc.

![Unnamed park 2021-04-18 19-24-34](https://user-images.githubusercontent.com/22866533/117549212-62137980-b039-11eb-9819-84bb75cfeabf.png)

**Comment by oli414** [comment]
> > ```
> > * Whilst new graphics do need to mimick the look and feel of the original graphics, we do not need to fully replicate the exact form and colors of each individual object. 
> > ```
> 
> So potentially the god-awful-looking looping coaster train could potentially get replaced with something closer to the rct1 version?

@Ryder17z yes but:
> **For this first stage, please refrain from discussing people their personal beliefs. We'll get to that once we've gathered enough input.**

**Comment by Gymnasiast** [comment]
> > ```
> > * Whilst new graphics do need to mimick the look and feel of the original graphics, we do not need to fully replicate the exact form and colors of each individual object. 
> > ```
> 
> So potentially the god-awful-looking looping coaster train could potentially get replaced with something closer to the rct1 version?

@Ryder17z The RCT2 train is realistic - clearly based on a type of train that Schwarzkopf used in the 80s. The RCT1 train is not.

**Comment by zrowny** [comment]
### Personal Beliefs
Obviously, the point of OpenGraphics is to eliminate OpenRCT2's dependence on the original assets from Rollercoaster Tycoon 2, and allow OpenRCT2 to be distributed completely without any non-free components. These new graphics should replicate the experience and function of the original graphics as closely as feasible. In some cases, this might mean that we need to make sure that the new objects have the exact same silhouette as the originals, but in general we should focus mostly on having the same "feel" as the originals. We should probably develop a specific style guide that goes into more detail in this area.

In addition, new graphics give us a good opportunity to expand the functionality of the original game. For example, I think for each track style, we should render every possible track piece in the game, not just those found in the original ride. Similarly, for every ride, we should render cars from all possible angles. (We certainly don't need to actually _enable_ every single track piece by default, but this would let an ["Allow All Track Pieces"](https://github.com/OpenRCT2/OpenRCT2/issues/5704#issue-238379221) cheat to actually be usable). This specific example aside, there are a number of areas in the base game where functionality could easily be expanded, if only there were graphics to support it. I think that, as a whole, we should lean towards rendering in excess, rather than the opposite.

Obviously though, this project needs to have priorities and structure. For a huge project like this, with so many different, specific tasks that need to be completed, having a good organizational structure is really important. Alongside developing a rendering pipeline, I think the most important focus in the beginning is working through all of the graphics in the original game that need to be replaced. I'm not sure what the best system is, but we should make a tracking system with a database of every set of sprites in the game that we need to make models for/render/draw. It's fairly straightforward to do this for all the objects, but organizing g1.dat is gonna be harder.

### Personal Experience
If you know me at all, you probably know that I started this project with _very_ underdeveloped template in Blender for rendering sprites. While it's been a long time since I actually worked on _this_ project, I'm still deeply experienced in 3d modelling and image rendering, and I have passable scripting abilities.

Ideally, we'd have a single unified pipeline for every 3D object we'll be rendering. Trying to manage different versions of Blender with different lighting and rendering setups and everything makes the project harder to manage and makes it harder for someone to jump in and contribute. Obviously that means we need to figure out the feasibility of using Blender 2.8+. We can have a more specific discussion about that elsewhere, but (without looking at things too specifically) it should definitely be possible to get basically identical results with Eevee (or with a custom rendering engine!) in 2.8+ as with the internal renderer in 2.79. Regardless of the specifics, I think it would be best to have a Blender Add-on that takes care of a lot of the work of the rendering process. Oli's [addon](https://github.com/oli414/Blender-RCT-Graphics) seems great so far, and I'm going to spend some time soon looking into developing that further.

**Comment by X123M3-256** [comment]
### Personal Beliefs

In my view the OpenGraphics project should focus on the G1 graphics first. This is the bare minimum for the game to start and be playable. I know that a lot of people have been looking at object files, but in my opinion, getting the game playable with OpenGraphics should be the first target. Right now, if you make a replacement object and contribute it to this repository, it won't appear in game until some indeterminate point in the future when the rest of the assets are replaced, which I think deters people from contributing.

I also think that, while we should aim to have an equivalent for every vanilla object, we need not stop there - I think the project should accept any additio

I think that we should go for a similar style as the original assets, but without necessarily making our sprites look identical to the originals. This would mean that some parks - particularly those that use scenery heavily - may look different when viewed with OpenGraphics if they were made for vanilla, but it affords us more flexibility, and makes things a lot easier (getting a perfect visual match for the original sprites is *hard*). In particular, there are some areas that I think the vanilla sprites could use improvement:

* Some vanilla sprites are disproportionately large or small compared to the real thing. For example, the twister coaster track is much wider than the corkscrew track, despite being the same size IRL. The worst offenders are the vanilla flat rides - the in game Top Spin takes only 8 guests, but the real thing takes 40.

To a certain extent this is necessary - the 4th dimension and vertical drop coaster may need to be squeezed down to fit within a tile (otherwise they will glitch) and replacements for the vanilla flat rides will have to keep the same footprint and capacity, otherwise they would not function as a replacement, but I think realistic proportions look best in most cases, and I would like to establish a nominal scale for use as a guideline.

* The default station object doesn't look realistic at all. I've never seen a coaster with an entrance building that looks like that, or a brick station platform.  I think the default station should look more like the one from RCT3. It is currently very common for the station platform to be made invisible and replaced with one built from scenery, but I don't think it should be necessary to do this to have something that looks reasonable.

* The flat ride base texture looks weird, I would go for a gray asphalt texture similar to the one used for paths.

* Some vanilla objects have inconsistent lighting. Looking at some of the air powered vertical coaster pieces, they don't match at all, and some track pieces are rendered with shadows where it really doesn't help (see the Virginia Reel). I think we should use the same lighting for every sprite.


I agree with @zrowny that we should render all track pieces and vehicle sprites - *that are reasonable* - I don't think we need to put minigolf holes on the B&M track, and heartline rolls are redundant on anything that already has inline twists. I don't think we should make them a separate ride type like @nfeho said, because that would add a lot of redundant track types, and it means that the "enable all drawable track pieces cheat" would not work as expected on saves imported from SV6, as they would have the old ride types. Instead, I would prefer it if we had a way to not show the extra sprites when vanilla assets are used (this means we don't have to worry about making our sprites match the originals, which makes the process *much* easier). Ideally, there would be a way to indicate which asset set a save file was created with, so that it can be viewed with the intended graphics set if available.


* Vanilla trees use the same sprite for all four angles. I don't think we should do this, having different sprites provides more variety (real trees don't all look exactly alike), and not all trees are sufficiently symmetrical that they would look the same from all different angles.

 In contrast to what @nfeho said, I don't think default trees should be recolorable - the reason being that most of the available colors look ridiculous on a tree, having to set the color to green every time you want to place a tree is an annoyance, and real trees aren't painted and you generally can't control the color. 

It might be interesting, however, if tree objects had multiple sprites that would be selected from at random when you place the tree- you could even make it so they change with the seasons. I don't think this kind of thing should be a priority though.

### Personal Experience

I was responsible for adding the RMC hybrid and single rail tracks to OpenRCT2. To this end, I have developed an entirely customized rendering pipeline which is able to match the vanilla sprites pretty well - although I have so far mostly looked at track, support, and peep sprites.

The advantage of this approach is its flexibility. Because I wrote the renderer from scratch, I can implement entirely specialized rendering logic. Some of the things my renderer does that would be challenging to achieve with a Blender based pipeline include:

* Explicit tracking of remappable regions - my renderer keeps track of which pixels belong to which remappable regions and uses a different palette for each, so that non-remappable palette colors are never confused with the remappable ones, an issue that I know people have run into trying to render sprites in Blender. Similarly, I can force the renderer to use a specific range of palette indices for specific colors, such as only grayscale (this has proved useful for peeps - I found it impossible to get the correct shading without restricting the render to use the specific range palette colors that the original sprites do, as there are too many similar colors in the palette).

* Many vanilla sprites have a distinct dark edge to them. @oli414 believes this was the result of anti-aliasing against a dark background, but I have found that trying to replicate the effect that way does not work well in practice - I find it is better if all edges are darkened, not just those that border background pixels. In addition, there is some evidence this is the case for vanilla sprites. My renderer uses the depth map to find edges internal to the sprite and applies a dark outline to them. This functionality can be turned on or off on a per material basis.

* Some sprites (particularly track and support sprites) need to tesselate smoothly with others. The use of non-local shading techniques such as ambient occlusion and shadows can cause problems for this. My renderer allows the use of a "ghost" track object which allows a sprite to be shaded as if there were an adjoining piece, without actually rendering that adjoining piece. This eliminates a lot of the issues I had where sprites did not join smoothly (but not all of them).

I also have software which almost completely automates the rendering of track sprites, including generating models for every element from a single straight piece of track, and then splitting up the final sprites into tile elements. I believe that a similar approach would work well for vehicle and terrain sprites, as in both cases you have a large number of sprites that are generated in a predictable way from a single model.

**Comment by oli414** [comment]
Alright, thanks for everyone's input, from here I'd like to split up the discussion into separate topics based on the goals and concerns shared in this thread.

So far we've had plenty of discussions on Gitter and on Discord, that makes it hard to look back at those discussions, and almost impossible for others to jump in if the conversation has already moved on. By creating separate discussion threads on Github we can greatly improve the efficiency of these discussions, and make it possible for everyone to chip in on the discussion.

Here are my suggestions for the separate topics we can discuss independently:
- **Rendering Methods**: which renderer will we use for our official setup?
- **Originality**: To what degree can we move away or expand upon the shapes, colors and options in the original game, and to what degree do we want to maintain it?
- **Priority**: What will be our roadmap, how will we split things up, and what parts do we want to do first?
- **Object Maker**: How will we go from renders, to a parkobj file and how will we integrate that into our workflow?
- **Model-Render Pipeline**: What tools/plugins will we provide, and what does it need to be capable of. Will, there be automated rendering involved, and how will we structure the repo?

**You may now discuss the topic suggestions in this thread. Is there any other topic that you think could use a separate discussion thread?**

Stay tuned for the creation of these discussion threads, in the meantime, feel free to add your believes and experiences if you haven't done so already.

**Comment by zrowny** [comment]
We clearly need a discussion on what rendering system we're going to use. I don't know if there's anything more critical for this project than settling this. 

I hope you don't mind if I just lay my thoughts out about the other things right here. I can certainly expand on these in separate topics if we have them.

I don't think we should be doing anything right now that isn't with the assumption that we'll be keeping everything to the original palette. It's too integral to the way that RCT2 renders things for that to easily change. I think it's not a bad idea to plan to render things in 2x scale at some point, but our focus can't be on expanding functionality until we actually make progress on what we already have to recreate.

As far as priority, we can obviously talk more specifically, but I think we should split things up between the stuff in g1.dat, and all the objects. Once we have a system in place for rendering, basically all the objects are straightforward to render and put into the game. Most of the stuff that makes up g1.dat, though, is more specialized, and may require a separate rendering process, especially for the track sprites.

Related to that is how our tools should actually work. Regardless of what specifics we settle on, there's no reason that a blender plugin can't do the whole process of making a json or parkobj file. I think @frutiemax is working on making a separate tool for making/viewing the json format objects, and that's probably really nice to have too, especially for previewing. But now that I have the json format mostly documented, I'd like to take a look at the plugins we have and expand them to be mo

**Comment by oli414** [comment]
> Also, I'd like to work on making a better listing of the things we need to work on for the project. Maybe we can talk about what the best format for that is, just a spreadsheet or something like Trello? Regardless, I'm gonna try to break down g1.dat a little better and in more detail than it has been (e.g. here's a description of all the animation sequences for peeps and the actual image layout, etc).

@zrowny if you want you can make an issue for that, I think it's a good idea to discuss that further. Having a roadmap and establishing the pipeline outside of the whole rendering thing is something that we can already determine right now.

**Comment by oli414** [comment]
Thanks everyone for the contributions, from here we'll take this conversation to separate discussions as discussed earlier.
